// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: core.proto

//go:build !protoopaque

package core

import (
	model "git.neds.sh/technology/pricekinetics/tools/codetest/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Event         *model.Event           `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRequest) GetEvent() *model.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UpdateRequest) SetEvent(v *model.Event) {
	x.Event = v
}

func (x *UpdateRequest) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.Event != nil
}

func (x *UpdateRequest) ClearEvent() {
	x.Event = nil
}

type UpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *model.Event
}

func (b0 UpdateRequest_builder) Build() *UpdateRequest {
	m0 := &UpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Event = b.Event
	return m0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateResponse) SetMessage(v string) {
	x.Message = v
}

type UpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message string
}

func (b0 UpdateResponse_builder) Build() *UpdateResponse {
	m0 := &UpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Message = b.Message
	return m0
}

type GetSportEventRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSportEventRequest) Reset() {
	*x = GetSportEventRequest{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSportEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSportEventRequest) ProtoMessage() {}

func (x *GetSportEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSportEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *GetSportEventRequest) SetEventID(v string) {
	x.EventID = v
}

type GetSportEventRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventID string
}

func (b0 GetSportEventRequest_builder) Build() *GetSportEventRequest {
	m0 := &GetSportEventRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventID = b.EventID
	return m0
}

type GetSportEventResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Event         *SportEvent            `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSportEventResponse) Reset() {
	*x = GetSportEventResponse{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSportEventResponse) ProtoMessage() {}

func (x *GetSportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSportEventResponse) GetEvent() *SportEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetSportEventResponse) SetEvent(v *SportEvent) {
	x.Event = v
}

func (x *GetSportEventResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.Event != nil
}

func (x *GetSportEventResponse) ClearEvent() {
	x.Event = nil
}

type GetSportEventResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *SportEvent
}

func (b0 GetSportEventResponse_builder) Build() *GetSportEventResponse {
	m0 := &GetSportEventResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Event = b.Event
	return m0
}

type SportEvent struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus string                 `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Markets       []*model.Market        `protobuf:"bytes,5,rep,name=Markets,proto3" json:"Markets,omitempty"`
	SportTypeID   string                 `protobuf:"bytes,6,opt,name=SportTypeID,proto3" json:"SportTypeID,omitempty"`
	SportName     string                 `protobuf:"bytes,7,opt,name=SportName,proto3" json:"SportName,omitempty"`
	Region        string                 `protobuf:"bytes,8,opt,name=Region,proto3" json:"Region,omitempty"`
	League        string                 `protobuf:"bytes,9,opt,name=League,proto3" json:"League,omitempty"`
	Round         string                 `protobuf:"bytes,11,opt,name=Round,proto3" json:"Round,omitempty"`
	Hidden        bool                   `protobuf:"varint,12,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportEvent) Reset() {
	*x = SportEvent{}
	mi := &file_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportEvent) ProtoMessage() {}

func (x *SportEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SportEvent) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SportEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SportEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SportEvent) GetBettingStatus() string {
	if x != nil {
		return x.BettingStatus
	}
	return ""
}

func (x *SportEvent) GetMarkets() []*model.Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *SportEvent) GetSportTypeID() string {
	if x != nil {
		return x.SportTypeID
	}
	return ""
}

func (x *SportEvent) GetSportName() string {
	if x != nil {
		return x.SportName
	}
	return ""
}

func (x *SportEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SportEvent) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

func (x *SportEvent) GetRound() string {
	if x != nil {
		return x.Round
	}
	return ""
}

func (x *SportEvent) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *SportEvent) SetID(v string) {
	x.ID = v
}

func (x *SportEvent) SetName(v string) {
	x.Name = v
}

func (x *SportEvent) SetStartTime(v string) {
	x.StartTime = v
}

func (x *SportEvent) SetBettingStatus(v string) {
	x.BettingStatus = v
}

func (x *SportEvent) SetMarkets(v []*model.Market) {
	x.Markets = v
}

func (x *SportEvent) SetSportTypeID(v string) {
	x.SportTypeID = v
}

func (x *SportEvent) SetSportName(v string) {
	x.SportName = v
}

func (x *SportEvent) SetRegion(v string) {
	x.Region = v
}

func (x *SportEvent) SetLeague(v string) {
	x.League = v
}

func (x *SportEvent) SetRound(v string) {
	x.Round = v
}

func (x *SportEvent) SetHidden(v bool) {
	x.Hidden = v
}

type SportEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID            string
	Name          string
	StartTime     string
	BettingStatus string
	Markets       []*model.Market
	SportTypeID   string
	SportName     string
	Region        string
	League        string
	Round         string
	Hidden        bool
}

func (b0 SportEvent_builder) Build() *SportEvent {
	m0 := &SportEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Markets = b.Markets
	x.SportTypeID = b.SportTypeID
	x.SportName = b.SportName
	x.Region = b.Region
	x.League = b.League
	x.Round = b.Round
	x.Hidden = b.Hidden
	return m0
}

type GetRacingEventRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRacingEventRequest) Reset() {
	*x = GetRacingEventRequest{}
	mi := &file_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRacingEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRacingEventRequest) ProtoMessage() {}

func (x *GetRacingEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRacingEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *GetRacingEventRequest) SetEventID(v string) {
	x.EventID = v
}

type GetRacingEventRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	EventID string
}

func (b0 GetRacingEventRequest_builder) Build() *GetRacingEventRequest {
	m0 := &GetRacingEventRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.EventID = b.EventID
	return m0
}

type GetRacingEventResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Event         *RacingEvent           `protobuf:"bytes,1,opt,name=Event,proto3" json:"Event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRacingEventResponse) Reset() {
	*x = GetRacingEventResponse{}
	mi := &file_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRacingEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRacingEventResponse) ProtoMessage() {}

func (x *GetRacingEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRacingEventResponse) GetEvent() *RacingEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetRacingEventResponse) SetEvent(v *RacingEvent) {
	x.Event = v
}

func (x *GetRacingEventResponse) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.Event != nil
}

func (x *GetRacingEventResponse) ClearEvent() {
	x.Event = nil
}

type GetRacingEventResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event *RacingEvent
}

func (b0 GetRacingEventResponse_builder) Build() *GetRacingEventResponse {
	m0 := &GetRacingEventResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Event = b.Event
	return m0
}

type RacingEvent struct {
	state          protoimpl.MessageState `protogen:"hybrid.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	StartTime      string                 `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	BettingStatus  string                 `protobuf:"bytes,4,opt,name=BettingStatus,proto3" json:"BettingStatus,omitempty"`
	Markets        []*model.Market        `protobuf:"bytes,5,rep,name=Markets,proto3" json:"Markets,omitempty"`
	RaceTypeID     string                 `protobuf:"bytes,6,opt,name=RaceTypeID,proto3" json:"RaceTypeID,omitempty"`
	RaceType       string                 `protobuf:"bytes,7,opt,name=RaceType,proto3" json:"RaceType,omitempty"`
	Venue          string                 `protobuf:"bytes,8,opt,name=Venue,proto3" json:"Venue,omitempty"`
	Region         string                 `protobuf:"bytes,9,opt,name=Region,proto3" json:"Region,omitempty"`
	RaceNumber     int64                  `protobuf:"varint,10,opt,name=RaceNumber,proto3" json:"RaceNumber,omitempty"`
	Distance       int64                  `protobuf:"varint,11,opt,name=Distance,proto3" json:"Distance,omitempty"` // metres
	TrackCondition string                 `protobuf:"bytes,12,opt,name=TrackCondition,proto3" json:"TrackCondition,omitempty"`
	RaceClass      string                 `protobuf:"bytes,13,opt,name=RaceClass,proto3" json:"RaceClass,omitempty"`
	Runners        []*Runner              `protobuf:"bytes,14,rep,name=Runners,proto3" json:"Runners,omitempty"` // ordered by Number
	Hidden         bool                   `protobuf:"varint,15,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RacingEvent) Reset() {
	*x = RacingEvent{}
	mi := &file_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RacingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RacingEvent) ProtoMessage() {}

func (x *RacingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RacingEvent) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RacingEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RacingEvent) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RacingEvent) GetBettingStatus() string {
	if x != nil {
		return x.BettingStatus
	}
	return ""
}

func (x *RacingEvent) GetMarkets() []*model.Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *RacingEvent) GetRaceTypeID() string {
	if x != nil {
		return x.RaceTypeID
	}
	return ""
}

func (x *RacingEvent) GetRaceType() string {
	if x != nil {
		return x.RaceType
	}
	return ""
}

func (x *RacingEvent) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *RacingEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RacingEvent) GetRaceNumber() int64 {
	if x != nil {
		return x.RaceNumber
	}
	return 0
}

func (x *RacingEvent) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RacingEvent) GetTrackCondition() string {
	if x != nil {
		return x.TrackCondition
	}
	return ""
}

func (x *RacingEvent) GetRaceClass() string {
	if x != nil {
		return x.RaceClass
	}
	return ""
}

func (x *RacingEvent) GetRunners() []*Runner {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *RacingEvent) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *RacingEvent) SetID(v string) {
	x.ID = v
}

func (x *RacingEvent) SetName(v string) {
	x.Name = v
}

func (x *RacingEvent) SetStartTime(v string) {
	x.StartTime = v
}

func (x *RacingEvent) SetBettingStatus(v string) {
	x.BettingStatus = v
}

func (x *RacingEvent) SetMarkets(v []*model.Market) {
	x.Markets = v
}

func (x *RacingEvent) SetRaceTypeID(v string) {
	x.RaceTypeID = v
}

func (x *RacingEvent) SetRaceType(v string) {
	x.RaceType = v
}

func (x *RacingEvent) SetVenue(v string) {
	x.Venue = v
}

func (x *RacingEvent) SetRegion(v string) {
	x.Region = v
}

func (x *RacingEvent) SetRaceNumber(v int64) {
	x.RaceNumber = v
}

func (x *RacingEvent) SetDistance(v int64) {
	x.Distance = v
}

func (x *RacingEvent) SetTrackCondition(v string) {
	x.TrackCondition = v
}

func (x *RacingEvent) SetRaceClass(v string) {
	x.RaceClass = v
}

func (x *RacingEvent) SetRunners(v []*Runner) {
	x.Runners = v
}

func (x *RacingEvent) SetHidden(v bool) {
	x.Hidden = v
}

type RacingEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID             string
	Name           string
	StartTime      string
	BettingStatus  string
	Markets        []*model.Market
	RaceTypeID     string
	RaceType       string
	Venue          string
	Region         string
	RaceNumber     int64
	Distance       int64
	TrackCondition string
	RaceClass      string
	Runners        []*Runner
	Hidden         bool
}

func (b0 RacingEvent_builder) Build() *RacingEvent {
	m0 := &RacingEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.StartTime = b.StartTime
	x.BettingStatus = b.BettingStatus
	x.Markets = b.Markets
	x.RaceTypeID = b.RaceTypeID
	x.RaceType = b.RaceType
	x.Venue = b.Venue
	x.Region = b.Region
	x.RaceNumber = b.RaceNumber
	x.Distance = b.Distance
	x.TrackCondition = b.TrackCondition
	x.RaceClass = b.RaceClass
	x.Runners = b.Runners
	x.Hidden = b.Hidden
	return m0
}

// Runner is a runner in a RacingEvent - ID matches the Selection ID in each market
type Runner struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number        int64                  `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Barrier       int64                  `protobuf:"varint,4,opt,name=Barrier,proto3" json:"Barrier,omitempty"`
	Jockey        string                 `protobuf:"bytes,5,opt,name=Jockey,proto3" json:"Jockey,omitempty"`
	Trainer       string                 `protobuf:"bytes,6,opt,name=Trainer,proto3" json:"Trainer,omitempty"`
	Weight        float64                `protobuf:"fixed64,7,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Scratched     bool                   `protobuf:"varint,8,opt,name=Scratched,proto3" json:"Scratched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runner) Reset() {
	*x = Runner{}
	mi := &file_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runner) ProtoMessage() {}

func (x *Runner) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Runner) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Runner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runner) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Runner) GetBarrier() int64 {
	if x != nil {
		return x.Barrier
	}
	return 0
}

func (x *Runner) GetJockey() string {
	if x != nil {
		return x.Jockey
	}
	return ""
}

func (x *Runner) GetTrainer() string {
	if x != nil {
		return x.Trainer
	}
	return ""
}

func (x *Runner) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Runner) GetScratched() bool {
	if x != nil {
		return x.Scratched
	}
	return false
}

func (x *Runner) SetID(v string) {
	x.ID = v
}

func (x *Runner) SetName(v string) {
	x.Name = v
}

func (x *Runner) SetNumber(v int64) {
	x.Number = v
}

func (x *Runner) SetBarrier(v int64) {
	x.Barrier = v
}

func (x *Runner) SetJockey(v string) {
	x.Jockey = v
}

func (x *Runner) SetTrainer(v string) {
	x.Trainer = v
}

func (x *Runner) SetWeight(v float64) {
	x.Weight = v
}

func (x *Runner) SetScratched(v bool) {
	x.Scratched = v
}

type Runner_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID        string
	Name      string
	Number    int64
	Barrier   int64
	Jockey    string
	Trainer   string
	Weight    float64
	Scratched bool
}

func (b0 Runner_builder) Build() *Runner {
	m0 := &Runner{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	x.Name = b.Name
	x.Number = b.Number
	x.Barrier = b.Barrier
	x.Jockey = b.Jockey
	x.Trainer = b.Trainer
	x.Weight = b.Weight
	x.Scratched = b.Scratched
	return m0
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x12\x04core\x1a\x11model/event.proto\"3\n" +
	"\rUpdateRequest\x12\"\n" +
	"\x05Event\x18\x01 \x01(\v2\f.model.EventR\x05Event\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"0\n" +
	"\x14GetSportEventRequest\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\tR\aEventID\"?\n" +
	"\x15GetSportEventResponse\x12&\n" +
	"\x05Event\x18\x01 \x01(\v2\x10.core.SportEventR\x05Event\"\xbb\x02\n" +
	"\n" +
	"SportEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tStartTime\x18\x03 \x01(\tR\tStartTime\x12$\n" +
	"\rBettingStatus\x18\x04 \x01(\tR\rBettingStatus\x12'\n" +
	"\aMarkets\x18\x05 \x03(\v2\r.model.MarketR\aMarkets\x12 \n" +
	"\vSportTypeID\x18\x06 \x01(\tR\vSportTypeID\x12\x1c\n" +
	"\tSportName\x18\a \x01(\tR\tSportName\x12\x16\n" +
	"\x06Region\x18\b \x01(\tR\x06Region\x12\x16\n" +
	"\x06League\x18\t \x01(\tR\x06League\x12\x14\n" +
	"\x05Round\x18\v \x01(\tR\x05Round\x12\x16\n" +
	"\x06Hidden\x18\f \x01(\bR\x06Hidden\"1\n" +
	"\x15GetRacingEventRequest\x12\x18\n" +
	"\aEventID\x18\x01 \x01(\tR\aEventID\"A\n" +
	"\x16GetRacingEventResponse\x12'\n" +
	"\x05Event\x18\x01 \x01(\v2\x11.core.RacingEventR\x05Event\"\xca\x03\n" +
	"\vRacingEvent\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tStartTime\x18\x03 \x01(\tR\tStartTime\x12$\n" +
	"\rBettingStatus\x18\x04 \x01(\tR\rBettingStatus\x12'\n" +
	"\aMarkets\x18\x05 \x03(\v2\r.model.MarketR\aMarkets\x12\x1e\n" +
	"\n" +
	"RaceTypeID\x18\x06 \x01(\tR\n" +
	"RaceTypeID\x12\x1a\n" +
	"\bRaceType\x18\a \x01(\tR\bRaceType\x12\x14\n" +
	"\x05Venue\x18\b \x01(\tR\x05Venue\x12\x16\n" +
	"\x06Region\x18\t \x01(\tR\x06Region\x12\x1e\n" +
	"\n" +
	"RaceNumber\x18\n" +
	" \x01(\x03R\n" +
	"RaceNumber\x12\x1a\n" +
	"\bDistance\x18\v \x01(\x03R\bDistance\x12&\n" +
	"\x0eTrackCondition\x18\f \x01(\tR\x0eTrackCondition\x12\x1c\n" +
	"\tRaceClass\x18\r \x01(\tR\tRaceClass\x12&\n" +
	"\aRunners\x18\x0e \x03(\v2\f.core.RunnerR\aRunners\x12\x16\n" +
	"\x06Hidden\x18\x0f \x01(\bR\x06Hidden\"\xc6\x01\n" +
	"\x06Runner\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Number\x18\x03 \x01(\x03R\x06Number\x12\x18\n" +
	"\aBarrier\x18\x04 \x01(\x03R\aBarrier\x12\x16\n" +
	"\x06Jockey\x18\x05 \x01(\tR\x06Jockey\x12\x18\n" +
	"\aTrainer\x18\x06 \x01(\tR\aTrainer\x12\x16\n" +
	"\x06Weight\x18\a \x01(\x01R\x06Weight\x12\x1c\n" +
	"\tScratched\x18\b \x01(\bR\tScratched2\xdb\x01\n" +
	"\aService\x125\n" +
	"\x06Update\x12\x13.core.UpdateRequest\x1a\x14.core.UpdateResponse\"\x00\x12J\n" +
	"\rGetSportEvent\x12\x1a.core.GetSportEventRequest\x1a\x1b.core.GetSportEventResponse\"\x00\x12M\n" +
	"\x0eGetRacingEvent\x12\x1b.core.GetRacingEventRequest\x1a\x1c.core.GetRacingEventResponse\"\x00B:Z8git.neds.sh/technology/pricekinetics/tools/codetest/coreb\x06proto3"

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_core_proto_goTypes = []any{
	(*UpdateRequest)(nil),          // 0: core.UpdateRequest
	(*UpdateResponse)(nil),         // 1: core.UpdateResponse
	(*GetSportEventRequest)(nil),   // 2: core.GetSportEventRequest
	(*GetSportEventResponse)(nil),  // 3: core.GetSportEventResponse
	(*SportEvent)(nil),             // 4: core.SportEvent
	(*GetRacingEventRequest)(nil),  // 5: core.GetRacingEventRequest
	(*GetRacingEventResponse)(nil), // 6: core.GetRacingEventResponse
	(*RacingEvent)(nil),            // 7: core.RacingEvent
	(*Runner)(nil),                 // 8: core.Runner
	(*model.Event)(nil),            // 9: model.Event
	(*model.Market)(nil),           // 10: model.Market
}
var file_core_proto_depIdxs = []int32{
	9,  // 0: core.UpdateRequest.Event:type_name -> model.Event
	4,  // 1: core.GetSportEventResponse.Event:type_name -> core.SportEvent
	10, // 2: core.SportEvent.Markets:type_name -> model.Market
	7,  // 3: core.GetRacingEventResponse.Event:type_name -> core.RacingEvent
	10, // 4: core.RacingEvent.Markets:type_name -> model.Market
	8,  // 5: core.RacingEvent.Runners:type_name -> core.Runner
	0,  // 6: core.Service.Update:input_type -> core.UpdateRequest
	2,  // 7: core.Service.GetSportEvent:input_type -> core.GetSportEventRequest
	5,  // 8: core.Service.GetRacingEvent:input_type -> core.GetRacingEventRequest
	1,  // 9: core.Service.Update:output_type -> core.UpdateResponse
	3,  // 10: core.Service.GetSportEvent:output_type -> core.GetSportEventResponse
	6,  // 11: core.Service.GetRacingEvent:output_type -> core.GetRacingEventResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
