syntax = "proto3";

package core;

import  "model/event.proto";

option go_package = "git.neds.sh/technology/pricekinetics/tools/codetest/core";

message UpdateRequest {
    model.Event Event = 1;
}

message UpdateResponse {
    string Message = 1;
}

message GetSportEventRequest {
    string EventID = 1;
}

message GetSportEventResponse {
    SportEvent Event = 1;
}

message SportEvent {
    string                  ID              = 1; 
    string                  Name            = 2;
    string                  StartTime       = 3;
    string                  BettingStatus   = 4;
    repeated model.Market   Markets         = 5; 
    string                  SportTypeID     = 6;
    string                  SportName       = 7;
    string                  Region          = 8;
    string                  League          = 9;
    string                  Round           = 11;
    bool                    Hidden          = 12;
}

message GetRacingEventRequest {
    string EventID = 1;
}

message GetRacingEventResponse {
    RacingEvent Event = 1;
}

message RacingEvent {
    string                  ID              = 1;
    string                  Name            = 2;
    string                  StartTime       = 3;
    string                  BettingStatus   = 4;
    repeated model.Market   Markets         = 5;
    string                  RaceTypeID      = 6;
    string                  RaceType        = 7;
    string                  Venue           = 8;
    string                  Region          = 9;
    int64                   RaceNumber      = 10;
    int64                   Distance        = 11; // metres
    string                  TrackCondition  = 12;
    string                  RaceClass       = 13;
    repeated Runner         Runners         = 14; // ordered by Number
    bool                    Hidden          = 15;
}

// Runner is a runner in a RacingEvent - ID matches the Selection ID in each market
message Runner {
    string  ID          = 1;
    string  Name        = 2;
    int64   Number      = 3;
    int64   Barrier     = 4;
    string  Jockey      = 5;
    string  Trainer     = 6;
    double  Weight      = 7;
    bool    Scratched   = 8;
}

service Service {
    // Update updates an Event and runs the pipeline of transformations
    rpc Update(UpdateRequest) returns (UpdateResponse) {}
    // GetSportEvent retrieves a model.Event from the database and returns a core.SportEvent - this is a more UserConsumable representation of the model that is specific to sport events
    rpc GetSportEvent(GetSportEventRequest) returns (GetSportEventResponse) {}
    // GetRacingEvent retrieves a model.Event from the database and returns a core.RacingEvent - this is a more UserConsumable representation of the model that is specific to racing events
    rpc GetRacingEvent(GetRacingEventRequest) returns (GetRacingEventResponse) {}
}